
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Oct 29 13:34:39 CST 2020
//----------------------------------------------------

package analizar_progra;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LLAVDER = 6;
  public static final int MENOS = 8;
  public static final int RFOR = 27;
  public static final int CADENA = 19;
  public static final int IGUAL = 28;
  public static final int DECIMAL = 17;
  public static final int DIVIDIDO = 10;
  public static final int RIMPRIMIR = 21;
  public static final int PARIZQ = 3;
  public static final int CONCAT = 11;
  public static final int PARDER = 4;
  public static final int UMENOS = 20;
  public static final int POR = 9;
  public static final int RCARACTER = 26;
  public static final int CARACTER = 18;
  public static final int IGUQUE = 30;
  public static final int EOF = 0;
  public static final int RELSE = 25;
  public static final int INCREMENTO = 12;
  public static final int RIF = 24;
  public static final int error = 1;
  public static final int MENQUE = 14;
  public static final int IDENTIFICADOR = 29;
  public static final int RMIENTRAS = 22;
  public static final int DECREMENTO = 13;
  public static final int ENTERO = 16;
  public static final int MAYQUE = 15;
  public static final int MAS = 7;
  public static final int RNUMERO = 23;
  public static final int LLAVIZQ = 5;
  public static final int PTCOMA = 2;
}

