package proyectocupjlexv2final;

import analizar_progra.Editor;
import analizadores.Lexico;
import analizadores.Sintactico;
import java.io.BufferedReader;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.io.StringReader;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JViewport;
import javax.swing.filechooser.FileNameExtensionFilter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author david
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }
    

    java.io.File DER;

    private void abrirArchivo(JFileChooser selectorArchivo) {
        DER = selectorArchivo.getSelectedFile();
        String contenido = "";
        if (!"".equals(getTexto())) {
            try {
                Scanner scn = new Scanner(DER);
                while (scn.hasNext()) {
                    contenido += scn.nextLine() + "\n";
                }
                agregarPestana(DER.getName(), contenido);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {

            try {
                Scanner scn = new Scanner(DER);
                while (scn.hasNext()) {
                    contenido += scn.nextLine() + "\n";
                }
                setTexto(contenido);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

    }

    private void agregarPestana(String titulo, String contenido) {
        marco.addTab(titulo, new JScrollPane(new JTextArea(contenido)));
    }

    public void probar() {
        JTextArea c = (JTextArea) (((JViewport) (((JScrollPane) marco.getComponentAt(marco.getSelectedIndex())).getViewport()))).getView();
        System.out.println(c.getText());
    }

    private void crearArchivo() {
        try {
            JFileChooser nuevo = new JFileChooser();
            FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivos .rep", "rep");
            nuevo.setFileFilter(filtro);
            nuevo.showSaveDialog(this);
            DER = nuevo.getSelectedFile();
            if (DER != null) {
                try (FileWriter save = new FileWriter(DER + ".rep")) {
                    save.write(getTexto());
                }
                JOptionPane.showMessageDialog(null, "Se a guardado el Archivo correctamente.", "Exito al Guardar", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Ha ocurrido un error al guardar el archivo, no se a guardado con exito.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void sobreescribirArchivo() {
        BufferedWriter bw = null;
        try {
            bw = new BufferedWriter(new FileWriter(DER));
            bw.write(getTexto());
            JOptionPane.showMessageDialog(null, "Se a guardado el Archivo correctamente.", "Exito al Guardar", JOptionPane.INFORMATION_MESSAGE);
            bw.close();
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            if (bw != null) {
                try {
                    bw.close();
                } catch (IOException ex) {
                    Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        salida = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        lexic = new javax.swing.JTextArea();
        marco = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        entrada = new javax.swing.JTextArea();
        Limpiar = new javax.swing.JButton();
        limpiar2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        nuevoArchivo = new javax.swing.JMenuItem();
        abrirArchivo = new javax.swing.JMenuItem();
        guardarArchivo = new javax.swing.JMenuItem();
        informacion = new javax.swing.JMenuItem();
        salir = new javax.swing.JMenuItem();
        lexico = new javax.swing.JMenu();
        botonAnalizar = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        salida.setColumns(20);
        salida.setRows(5);
        jScrollPane3.setViewportView(salida);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lexic.setEditable(false);
        lexic.setColumns(20);
        lexic.setForeground(new java.awt.Color(255, 0, 51));
        lexic.setRows(5);
        lexic.setText("Salida Lexica:");
        jScrollPane1.setViewportView(lexic);

        entrada.setColumns(20);
        entrada.setRows(5);
        jScrollPane2.setViewportView(entrada);

        marco.addTab("tab1", jScrollPane2);

        Limpiar.setText("Limpiar Salida");
        Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarActionPerformed(evt);
            }
        });

        limpiar2.setText("Limpiar Entrada");
        limpiar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiar2ActionPerformed(evt);
            }
        });

        jMenu1.setText("     Archivo     ");

        nuevoArchivo.setText("Nuevo Archivo");
        nuevoArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoArchivoActionPerformed(evt);
            }
        });
        jMenu1.add(nuevoArchivo);

        abrirArchivo.setText("Abrir Archivo");
        abrirArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirArchivoActionPerformed(evt);
            }
        });
        jMenu1.add(abrirArchivo);

        guardarArchivo.setText("Guardar");
        guardarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarArchivoActionPerformed(evt);
            }
        });
        jMenu1.add(guardarArchivo);

        informacion.setText("Acerca de");
        informacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                informacionActionPerformed(evt);
            }
        });
        jMenu1.add(informacion);

        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        jMenu1.add(salir);

        jMenuBar1.add(jMenu1);

        lexico.setText("     Acciones    ");

        botonAnalizar.setText("Analizar");
        botonAnalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAnalizarActionPerformed(evt);
            }
        });
        lexico.add(botonAnalizar);

        jMenuItem1.setText("Salida Lexica");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        lexico.add(jMenuItem1);

        jMenuItem2.setText("imagen al azar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        lexico.add(jMenuItem2);

        jMenuBar1.add(lexico);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(marco, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
                    .addComponent(Limpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(limpiar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(marco))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(Limpiar)
                        .addGap(18, 18, 18)
                        .addComponent(limpiar2)
                        .addGap(0, 174, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nuevoArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoArchivoActionPerformed
        // TODO add your handling code here:
        crearArchivo();
    }//GEN-LAST:event_nuevoArchivoActionPerformed

    private void abrirArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirArchivoActionPerformed
        // TODO add your handling code here:
        JFileChooser selectorArchivo = new JFileChooser();
        selectorArchivo.setFileSelectionMode(JFileChooser.FILES_ONLY);
        if (selectorArchivo.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            abrirArchivo(selectorArchivo);
        }
    }//GEN-LAST:event_abrirArchivoActionPerformed

    private void guardarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarArchivoActionPerformed
        // TODO add your handling code here:
        if (DER != null) {
            int n = JOptionPane.showConfirmDialog(null, "El archivo sera modificado permanentemente, desea continuar?", "Verificacion de Guardado", JOptionPane.YES_NO_OPTION);
            if (true) {
                sobreescribirArchivo();
            }
        } else {
            crearArchivo();
        }
    }//GEN-LAST:event_guardarArchivoActionPerformed

    private void informacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_informacionActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_informacionActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // TODO add your handling code here:
        int n = JOptionPane.showConfirmDialog(null, "Desea Cerrar la Aplicacion?", "Salir", JOptionPane.YES_NO_OPTION);
        if (n == 0) {
            System.exit(0);
        }

    }//GEN-LAST:event_salirActionPerformed

    String path = System.getProperty("user.dir");

    private ArrayList<String> obtenerficheros(String tipo) {
        ArrayList<String> rutas = new ArrayList();
        File dir = new File(path + "\\src\\" + tipo);
        String[] ficheros = dir.list();
        if (ficheros == null) {
            System.out.println("No hay ficheros en el directorio especificado");
        } else {
            for (String fichero : ficheros) {
                System.out.println("/" + tipo + "/" + fichero);
                rutas.add("/" + tipo + "/" + fichero);
            }
        }
        return rutas;
    }


    private void botonAnalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAnalizarActionPerformed
        // TODO add your handling code here:
        Lexico lexico;
        Sintactico analizar = null;
        try {
            String input = getTexto();
            lexico = new Lexico(new BufferedReader(new StringReader(input)));
            analizar = new Sintactico(lexico);
            try {
                analizar.parse();
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }

    }//GEN-LAST:event_botonAnalizarActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        String input = getTexto();
        Editor editor = new Editor();
        editor.setFuente(input);
        editor.accion();
        Imprimir_codigo(editor.getDestino());
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarActionPerformed
        // TODO add your handling code here:
        lexic.setText("");
    }//GEN-LAST:event_LimpiarActionPerformed

    private void limpiar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiar2ActionPerformed
        // TODO add your handling code here:
        entrada.setText("");
    }//GEN-LAST:event_limpiar2ActionPerformed

    private void setTexto(String texto) {
        JTextArea c = (JTextArea) (((JViewport) (((JScrollPane) marco.getComponentAt(marco.getSelectedIndex())).getViewport()))).getView();
        c.setText(texto);
    }

    private String getTexto() {
        JTextArea c = (JTextArea) (((JViewport) (((JScrollPane) marco.getComponentAt(marco.getSelectedIndex())).getViewport()))).getView();
        return c.getText();
    }

    public static void Imprimir(String impresion) {
        lexic.setText(lexic.getText() + "\n" + impresion);
    }
    
        public static void Imprimir_codigo(String impresion) {
            lexic.setText(lexic.getText() + "\n" + impresion);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Limpiar;
    private javax.swing.JMenuItem abrirArchivo;
    private javax.swing.JMenuItem botonAnalizar;
    private javax.swing.JTextArea entrada;
    private javax.swing.JMenuItem guardarArchivo;
    private javax.swing.JMenuItem informacion;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    public static javax.swing.JTextArea lexic;
    private javax.swing.JMenu lexico;
    private javax.swing.JButton limpiar2;
    private javax.swing.JTabbedPane marco;
    private javax.swing.JMenuItem nuevoArchivo;
    private javax.swing.JTextArea salida;
    private javax.swing.JMenuItem salir;
    // End of variables declaration//GEN-END:variables
}
